configfile:
  - defaults/parameters.yaml
  - nextstrain_profiles/nextstrain-gisaid-preprocess/builds.yaml

keep-going: True
printshellcmds: True
show-failed-logs: True
restart-times: 1
reason: True
stats: stats.json
